#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config border_width         1
gap=5

bspc config normal_border_color '#888888'
bspc config focused_border_color '#dddddd'

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

# remove window gap at screen edges
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

# rules
bspc rule -a emacs state=tiled
